---
title: "forward elimination"
author: "Jiayi Shen"
date: "12/8/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r load data}
can_reg = read.csv("Cancer_Registry.csv")

#fisrt filtering out redundant variables 
#recode categorical variables 
can_reg_omit = can_reg %>% 
  janitor::clean_names() %>% 
  select( -pct_some_col18_24, -pct_no_hs18_24, -pct_hs18_24, -pct_bach_deg18_24, -avg_ann_count, -incidence_rate, -avg_deaths_per_year, -med_income, -pop_est2015, -median_age_male, -median_age_female, -percent_married, -pct_employed16_over, -pct_private_coverage, -pct_private_coverage_alone, -pct_emp_priv_coverage, -pct_public_coverage, -pct_black, -pct_asian, -pct_other_race) %>% 
  filter(median_age < 100) %>% 
  select(geography, target_death_rate, binned_inc, everything()) %>% 
  na.omit() 
  # %>% mutate(pct_white = ifelse(pct_white > 80, 1, 0))
```

## AIC-based Forward selection


```{r}
#define the upper limit of forward selection
#since we have not decide how does binned income enter the model, 
#so we firstly try modeling without binned income. 

upper_fit = 
  lm(target_death_rate ~ poverty_percent + study_per_cap + median_age + avg_household_size + pct_hs25_over + pct_bach_deg25_over + pct_unemployed16_over +pct_public_coverage_alone + pct_white + pct_married_households + birth_rate, data = can_reg_omit)

# forward selection based on AIC.
fitstart = lm(target_death_rate ~1, data = can_reg_omit)
step(fitstart, direction = "forward", scope = formula(upper_fit))
```

Forward selection gives the following model:
`target_death_rate ~ pct_bach_deg25_over + pct_married_households + 
    pct_hs25_over + pct_unemployed16_over + birth_rate + median_age + 
    pct_public_coverage_alone + avg_household_size`
which include 8 variables. 

###Check Multicolinearity
```{r}
forward1 = lm(formula = target_death_rate ~ pct_bach_deg25_over + pct_married_households + 
    pct_hs25_over + pct_unemployed16_over + birth_rate + median_age + 
    pct_public_coverage_alone + avg_household_size, data = can_reg_omit)
#check multicolinearity
faraway::vif(forward1) %>% knitr::kable()
```
All variables in this model have VIF less than 5. Generally good.


